version: "3"
services:

  db:
    image: mysql:8.0.32
    ports:
      - "30000:3306"
    environment:
      MYSQL_DATABASE: webapp
      # MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: mypassword
    volumes:
      - "./db.sql:/docker-entrypoint-initdb.d/db.sql"
    # networks:
    # - webapp_network

  app:
    build: .
    # links:
    #   - db
    command: sh -c 'sleep 30 && python app.py'
    depends_on:
      - db
    ports:
      - "5000:5000"
    # networks:
    # - webapp_network

# networks:
#   webapp_network:
#     external: true